
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  engine: "classic",
  datasource: {
    // CLI commands (migrate, db seed, studio) need a direct, non-pooled
    // connection — Neon's pooled connection doesn't support the advisory
    // lock Prisma Migrate takes. The running app still uses the pooled
    // DATABASE_URL declared in prisma/schema.prisma.
    url: env("DIRECT_URL"),
  },
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
});
